export const INCREMENT = "INCREMENT"
export const LOAD_MARKDOWNS_BASIC = "LOAD_MARKDOWNS_BASIC"
export const LOAD_MARKDOWNS_CHEAT = "LOAD_MARKDOWNS_CHEAT"
export const SELECTED_MARKDOWNS = "SELECTED_MARKDOWNS"